### ISSUE TITLE
CMake Error: install TARGETS given no RUNTIME DESTINATION

### ISSUE THREAD

**Issue by webspacecreations** [audetto/AppleWin#9]
Latest Raspbian distro (Debian) running gcc 8.3.0 and cmake 3.13.4. Upon `cmake ..` I get the following output:

CMAKE_BUILD_TYPE:                RELEASE
CMAKE_CXX_FLAGS:                  -Wno-multichar -Werror=return-type
CMAKE_CXX_FLAGS_RELEASE:         -O3 -DNDEBUG
CMAKE_CXX_FLAGS_DEBUG:           -g
CMAKE_CXX_FLAGS_RELWITHDEBINFO:  -O2 -g -DNDEBUG
-- Boost version: 1.67.0
CMake Error at source/CMakeLists.txt:88 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "appleii".

-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
CMake Error at source/frontends/ncurses/CMakeLists.txt:45 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "applen".

CMake Error at source/frontends/qapple/CMakeLists.txt:39 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "qapple".

-- Configuring incomplete, errors occurred!

Before I try to edit the 3 indicated CMakeLists.txt files, is it possible to pass the TARGETS value as a flag for cmake (or something similar)?

**Comment by audetto** [comment]
It is fixed here

https://github.com/audetto/AppleWin/commit/13edefa6e04258b6ed6a21bb80823984234d9230

Newer versions of cmake do not need it (I was using 3.16).

**Comment by webspacecreations** [comment]
That did indeed fix the issue, but opened a big new can of worms with lots of invalid header paths. These are all now fixed. Would have committed, but don't have permission (see attached file). It was rather anti-climactic, however, as all I got was a shared object (libappleii.so) vs an appleii executable.

[source_paths_fixed.gz](https://github.com/audetto/AppleWin/files/5337940/source_paths_fixed.gz)

**Comment by audetto** [comment]
Why dont you fork it and propose a PR?

**Comment by audetto** [comment]
I looked at your changes, but I think they are a symptom of something not right with your building environment.
I can compile it as is on Ubuntu, Fedora and a RapsberryPi.

Can you tell me exactly how you compile it from a fresh checkout?

**Comment by webspacecreations** [comment]
git clone --recursive https://github.com/audetto/AppleWin.git (first time I've tried with the recursive flag)
cd AppleWin
mkdir build
cd build
cmake .. (output is Build files have been written to: /home/pi/Projects/AppleWin/build)
make

Alright, it works! (./qapple). Very clean build (only 2 warnings is the fewest I've seen recently on many emulators I've compiled). Based on how much more verbose this iteration was, I'm guessing the --recursive flag grabbed a few things it hadn't the previous time.

FYI, benchmark on a 4GB RPi4 modestly overclocked to 2Ghz is:
Pure Video FPS:	170631
Pure CPU MHz:	2.3 (video update)
Pure CPU MHz:	48.8 (full-speed)

EXPECTED AVERAGE VIDEO GAME
PERFORMANCE: 96 FPS

Preliminary feedback: Cycling through the various video modes (F9) results in a segmentation fault. Restarting it and hitting F9 kills the emulator again (showing Monochrome Green). I can select a different option in the GUI (btw, White has a typo as Monotchrome White), but now the emulator crashes once a game (Mario Bros) enters hires mode (it did work before I tried the different video modes). After some testing, it looks like RGB mode (possibly others) is a problem. Sound DOES work on the Pi IF I disable Enhanced Speed under Disks.

While I'm not a big fan of Qt (definitely the most dependencies I've encountered recently), I totally support the idea of a compatibility layer to stay concurrent with the parent Windows-only distro. I think your approach is the only sane one (well, other than AppleWin devs committing to broader platform support). If there's anything you need help with, let me know. If an SDL variant of your project fell in your lap, would you consider switching from Qt (probably a bigger issue on Pi than a proper desktop environment)? Thanks for the considerable effort!

**Comment by audetto** [comment]
Yes about seg fault.
There has been a lot of work on rgb cards recently in AW and I have postponed a proper check. It compiles but it crashes. I must miss some initialisation. Will fix it.

SDL: I have written most of it: https://github.com/audetto/AppleWin/tree/sdl.
not sure in which state it is, need to resuscitate it.

**Comment by audetto** [comment]
Seg fault fixed at https://github.com/audetto/AppleWin/commit/039bfc04c31aa969350a97a39137a38ea792c60b
See if there are any other issues.

**Comment by webspacecreations** [comment]
Looks to be fixed! Launching with Enhanced speed for disks DISABLED is key to getting audio. I even ran the SAM demo with SAM/DAC in Slot 5 and tried it out in Apple II+ with language card. I'd have to download some dealer test disks to do any more extensive testing, but at a glance, this looks to be the most polished (and feature capable) Apple II emulator available for Pi/Linux.

Minor suggestion for improvement would be putting a Quit option under the File menu.

I'll take a look at the SDL branch. Being able to rapidly build a UI in Qt has some definite perks as evidenced by what you've done, but having to run in windowed mode (and even a window within a window) looks to be a drawback. I'm also guessing fullscreen isn't feasible. SDL might also reduce CPU consumption (hovers around 30% when running).

It'd be awesome if the emulator auto-paused after a preset period of user inactivity (like a power saver) as pausing the emulator dramatically cuts CPU utilization.

Nice work!

**Comment by webspacecreations** [comment]
Tried to grab the SDL tree, but either I'm doing something wrong or it's some kind of SDL/Qt hybrid. Here's what I've done:
git clone -b sdl --recursive https://github.com/audetto/AppleWin.git
cd AppleWin
git checkout sdl (I'm informed that I'm already in sdl branch and it's up to date)

Upon compiling, I'm still getting the Qt window, menu system, and About Qt menu option. It's clearly different code (e.g. some of the card slot options are missing), but I was a little surprised to still see the Qt widgets. Not complaining all that much (there's a lot to digest with what you've done in the main branch), but also not sure what the latest state of Qt licensing is on non-Linux platforms.

**Comment by audetto** [comment]
Move SDL to https://github.com/audetto/AppleWin/issues/10

**Comment by audetto** [comment]
The SDL version creates a ``sa2`` executable: https://github.com/audetto/AppleWin/blob/sdl/source/frontends/sa2/CMakeLists.txt

Without Qt, you will not be able to configure anything as SDL does not provide any widget.
Liapple implemented a text menu in SDL, but I'd rather not to.
You will have to use cmd line switches or manually change the config file (which is not always obvious).
